/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IChainLinkPriceOracle,
  IChainLinkPriceOracleInterface,
} from "../IChainLinkPriceOracle";

const _abi = [
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IChainLinkPriceOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IChainLinkPriceOracleInterface {
    return new utils.Interface(_abi) as IChainLinkPriceOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainLinkPriceOracle {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IChainLinkPriceOracle;
  }
}
